export const packagesData = [
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '1',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '2',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '3',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '4',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '9',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '5',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '6',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '7',
    onEdit: () => undefined,
    onDelete: () => undefined
  },
  {
    img: 'https://placeimg.com/400/225/arch',
    title: 'Moroccan bath, scrub and more',
    reviews: 10,
    oldPrice: 150,
    price: 100,
    broughtNumber: 3,
    discount: 20,
    totalReviews: 50,
    id: '8',
    onEdit: () => undefined,
    onDelete: () => undefined
  }
]
